package com.aiait.eflow.common;

public interface ModuleOperateName {
   int MODULE_FORM_INVERTORY = 7;
   int MODULE_MY_APPLIED_FORM = 8;
   int MODULE_MY_TASK = 9;
   int MODULE_MY_HANDLED_FORM = 10;
   
   int MODULE_FORM_INQUIRY = 11;
   int MODULE_OVERDUE_FORM = 12;

   int MODULE_FLOW_MANAGE = 13;
   int MODULE_FORM_MANAGE = 14;
   
   int MODULE_DELEGATION_CONFIG = 15;
   int MODULE_DELEGATION_HISTORY = 16;
   int MODULE_DEPUTY_HANDLE = 17;
   
   int MODULE_SYSTEM_OWNER = 21;
   int MODULE_DB_OWNER = 22;
   int MODULE_AUTHORIZED_GROUP = 23;
   int MODULE_EMAIL_TEMPLATE = 24;
   int MODULE_HOLIDAY_MANAGE = 25;
   int MODULE_AUTHORITY_MANAGE = 26;
   int MODULE_DATA_DICTIONARY = 27;
   int MODULE_COMMON_QUERY = 28;
   int MODULE_USER_MANAGE = 29;
   int MODULE_TEAM_MANAGE = 30;
   int MODULE_PROJECT_MANAGE = 31;
   int MODULE_MEAL_ALLOWANCE_CONFIRM = 32;
   int MODULE_BASE_DATA_MANAGE = 35;
   int MODULE_FORM_TYPE = 36;
   int MODULE_LEAVE_DETAIL_REPORT = 41;
   int MODULE_LEAVE_SUMMARY_REPORT = 42;
   
   int OPER_FORM_INQUIRY_TS = 1;
   int OPER_FORM_INQUIRY_ACCOUNT = 2;
   int OPER_FORM_INQUIRY_ADMIN = 3;
   int OPER_FORM_INQUIRY_HR = 4;
   int OPER_FORM_INQUIRY_EFLOW = 5;
   int OPER_FORM_INQUIRY_UNLOCK = 6;
   int OPER_FORM_INQUIRY_REASSIGN = 7;
   
   int OPER_FLOW_ADD = 1;
   int OPER_FLOW_DELETE = 2;
   int OPER_FLOW_UPDATE = 3;
   int OPER_FLOW_DESIGN = 4;
   int OPER_FLOW_QUERY = 5;
   int OPER_FLOW_COPY = 6;
   
   int OPER_FORM_ADD = 1;
   int OPER_FORM_DELETE = 2;
   int OPER_FORM_UPDATE = 3;
   int OPER_FORM_DESIGN = 4;
   int OPER_FORM_QUERY = 5;
   int OPER_FORM_COPY = 6;
   int OPER_FORM_PUBLISH = 7;
   int OPER_FORM_QUERY_TS = 8;
   int OPER_FORM_QUERY_ADMIN = 9;
   int OPER_FORM_QUERY_ACCOUNT = 10;
   int OPER_FORM_QUERY_HR = 11;
   int OPER_FORM_QUERY_EFLOW = 12;
   
   int OPER_DEPUTY_CONFIG_QUERY = 1;
   int OPER_DEPUTY_CONFIG_ADD = 2;
   int OPER_DEPUTY_CONFIG_REVOKE = 3;
   int OPER_DEPUTY_CONFIG_ADD_SELF = 4;
   int OPER_DEPUT_CONFIG_REVOKE = 5;
   int OPER_DEPUTY_REASSIGN = 6;
   
   int OPER_DEPUTY_HANDLE_QUERY_ALL = 1;
   int OPER_DEPUTY_HANDLE_QUERY_SELF = 2;
   
   int OPER_SYSTEM_OWNER_QUERY = 1;
   int OPER_SYSTEM_OWNER_ADD = 2;
   int OPER_SYSTEM_OWNER_DELETE = 3;
   int OPER_SYSTEM_OWNER_UPDATE = 4;
   
   int OPER_DB_OWNER_QUERY = 1;
   int OPER_DB_OWNER_ADD = 2;
   int OPER_DB_OWNER_DELETE = 3;
   int OPER_DB_OWNER_UPDATE = 4;
   
   int OPER_AUTHORIZED_GROUP_QUERY = 1;
   int OPER_AUTHORIZED_GROUP_ADD = 2;
   int OPER_AUTHORIZED_GROUP_DELETE = 3;
   int OPER_AUTHORIZED_GROUP_UPDATE = 4;
   int OPER_AUTHORIZED_GROUP_MEMBER = 5;
   
   int OPER_EMAIL_TEMPLATE_QUERY = 1;
   int OPER_EMAIL_TEMPLATE_ADD = 2;
   int OPER_EMAIL_TEMPLATE_DELETE = 3;
   int OPER_EMAIL_TEMPLATE_UPDATE = 4;
   
   int OPER_AUTHORITY_MANAGE_QUERY = 1;
   int OPER_AUTHORITY_MANAGE_ADD = 2;
   int OPER_AUTHORITY_MANAGE_DELETE = 3;
   int OPER_AUTHORITY_MANAGE_UPDATE = 4;
   int OPER_AUTHORITY_MANAGE_PURVIEW = 5;
   int OPER_AUTHORITY_MANAGE_MEMBER = 6;
   
   int OPER_DATA_DICTIONARY_QUERY = 1;
   int OPER_DATA_DICTIONARY_ADD = 2;
   int OPER_DATA_DICTIONARY_UPDATE = 3;
   
   int OPER_USER_QUERY = 1;
   int OPER_USER_ADD = 2;
   int OPER_USER_EDIT = 3;
   int OPER_USER_DELETE = 4;
   int OPER_USER_LEAVE_MAINTAIN = 5;
   
   int OPER_TEAM_QUERY = 1;
   int OPER_TEAM_ADD = 2;
   int OPER_TEAM_EDIT = 3;
   int OPER_TEAM_DELETE = 4;
   int OPER_TEAM_CONFIG = 5;
   
   int OPER_PROJECT_QUERY = 1;
   int OPER_PROJECT_ADD = 2;
   int OPER_PROJECT_EDIT = 3;
   int OPER_PROJECT_DELETE = 4;
   
   int OPER_FORM_TYPE_QUERY = 1;
   int OPER_FORM_TYPE_ADD = 2;
   int OPER_FORM_TYPE_EDIT = 3;
   int OPER_FORM_TYPE_DELETE = 4;
   
   int OPER_LEAVE_DETAIL_ALL= 1;
   int OPER_LEAVE_DETAIL_TL = 2;
   int OPER_LEAVE_SUMMARY_ALL= 1;
   int OPER_LEAVE_SUMMARY_TL = 2; 
}
